### ISSUE TITLE
DescribeVxnets parameter error

### ISSUE THREAD

**Issue by jolestar** [yunify/hostnic-cni#14]
DescribeVxnets parameter vxnets is empty string some time, cause "AuthFailure, signature not matched error".

https://api.qingcloud.com:443/iaas?action=DescribeVxnets&limit=20&offset=0&verbose=0 &vxnets.1=&zone=pek3a

**Comment by martinyunify** [comment]
I think this is because parameter is empty. e.g. vxnets.1=

**Comment by jolestar** [comment]
@martinyunify  I think this is not a sdk bug.  sdk's all parameter is pointer。

**Comment by martinyunify** [comment]
We've enhanced the parameter validation and it never happened since then. Close this issue.
